services:
  frontend:
    image: 312290079196.dkr.ecr.eu-central-1.amazonaws.com/toycars-frontend:toycars-frontend-img
    ports:
      - "8080:8080"
    networks:
      - appnetwork
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: curl -f http://localhost:8080/ || exit 1
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s

  backend:
    image: 312290079196.dkr.ecr.eu-central-1.amazonaws.com/toycars-backend:toycars-backend-img
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks: 
      - appnetwork
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      disable: true
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - appnetwork
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      disable: true
    depends_on:
      - frontend
      - backend

  

networks:
  appnetwork:
    driver: overlay
           